services:
  - type: web
    name: n8n
    env: docker
    plan: free
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-database
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-database
          property: password
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com/

databases:
  - name: n8n-database
    plan: free
